export const action= {
    SET_ITEMS: "SET_ITEMS",
    SET_ISLOADING: "SET_ISLOADING",
    SET_ISERROR: "SET_ISERROR",
    SET_TOTAL: "SET_TOTAL",
    INCREASE: "INCREASE",
    DECREASE: "DECREASE",
    CLEAR_ITEMS: "CLEAR_ITEMS",
    DELETE_ITEM: "DELETE_ITEM"
}